### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Could not read key

### ISSUE THREAD

**Issue by TheBlindM** [warp-tech/russh#164]
**desc**:
I use authenticate_ There was a problem with the password, I don't know how to solve it. Is this related to the host key or how can I disable 'StrictHostKeyChecking'

**code**:
```
pub async fn con() {
	let config = russh::client::Config {
		preferred: Preferred {
			key: &[
				key::ED25519,
				key::RSA_SHA2_256,
				key::RSA_SHA2_512,
				key::SSH_RSA,
			],
			..<_>::default()
		},
		..Default::default()
	};

	let config = Arc::new(config);
	let sh = Client {};

	let mut session = client::connect(config, ("XXXXXX", 22), sh).await.unwrap();

	if session.authenticate_password("root", "XXXXX").await.unwrap() {
		let mut channel = session.channel_open_session().await.unwrap();
		channel.data(&b"Hello, world!"[..]).await.unwrap();
		if let Some(msg) = channel.wait().await {
			println!("{:?}", msg)
		}
	}
}

```

**Err**:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Could not read key

Stack backtrace:
   0: std::backtrace_rs::backtrace::dbghelp::trace
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2: std::backtrace::Backtrace::create
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library\std\src\backtrace.rs:332
   3: std::backtrace::Backtrace::capture
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library\std\src\backtrace.rs:298
   4: anyhow::error::impl$2::from<enum2$<russh::Error> >
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\anyhow-1.0.71\src\error.rs:547
   5: core::result::impl$27::from_residual<tuple$<russh::session::NewKeys,app::core::connect::Client>,enum2$<russh::Error>,anyhow::Error>
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\core\src\result.rs:1961
   6: russh::client::impl$6::server_key_check::async_fn$0<app::core::connect::Client>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\russh-0.37.1\src\client\mod.rs:1090
   7: russh::client::reply::async_fn$0<app::core::connect::Client>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\russh-0.37.1\src\client\mod.rs:1188
   8: russh::client::impl$5::run::async_fn$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\russh-0.37.1\src\client\mod.rs:791
   9: core::future::future::impl$1::poll<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\core\src\future\future.rs:125
  10: tokio::runtime::task::core::impl$6::poll::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\core.rs:311
  11: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> > 
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\loom\std\unsafe_cell.rs:14
  12: tokio::runtime::task::core::Core<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\core.rs:300
  13: tokio::runtime::task::harness::poll_future::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runti
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\harness.rs:476
  14: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > >,tokio::runtime::task::harness::poll_future::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::r
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\core\src\panic\unwind_safe.rs:271
  15: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panicking.rs:500
  16: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$2::drop_join_handle_slow::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<
  17: std::panicking::try<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<russh:
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panicking.rs:464
  18: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::st
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panic.rs:142
  19: tokio::runtime::task::harness::poll_future<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::schedul
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\harness.rs:464
  20: tokio::runtime::task::harness::Harness<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\harness.rs:198
  21: tokio::runtime::task::harness::Harness<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\harness.rs:152
  22: tokio::runtime::task::raw::poll<core::pin::Pin<alloc::boxed::Box<enum2$<russh::client::impl$5::run::async_fn_env$0<app::core::connect::Client,tokio::net::tcp::stream::TcpStream> >,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_t
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\raw.rs:276
  23: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\raw.rs:200
  24: tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >::run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\mod.rs:400
  25: tokio::runtime::scheduler::multi_thread::worker::impl$1::run_task::closure$0
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\scheduler\multi_thread\worker.rs:576
  26: tokio::runtime::coop::with_budget
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\coop.rs:107
  27: tokio::runtime::coop::budget
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\coop.rs:73
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\scheduler\multi_thread\worker.rs:575
  29: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\scheduler\multi_thread\worker.rs:526
  30: tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure$0
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\scheduler\multi_thread\worker.rs:491
  31: tokio::runtime::context::scoped::Scoped<enum2$<tokio::runtime::scheduler::Context> >::set<enum2$<tokio::runtime::scheduler::Context>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0,tuple$<> >
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\context\scoped.rs:40
  32: tokio::runtime::context::set_scheduler::closure$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\context.rs:176
  33: std::thread::local::LocalKey<tokio::runtime::context::Context>::try_with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>,tuple$
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\thread\local.rs:270
  34: std::thread::local::LocalKey<tokio::runtime::context::Context>::with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>,tuple$<> >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\thread\local.rs:246
  35: tokio::runtime::context::set_scheduler<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\context.rs:176
  36: tokio::runtime::scheduler::multi_thread::worker::run::closure$0
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\scheduler\multi_thread\worker.rs:486
  37: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::worker::run::closure_env$0,tuple$<> >
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\context\runtime.rs:65
  38: tokio::runtime::scheduler::multi_thread::worker::run
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\scheduler\multi_thread\worker.rs:478
  39: tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure$0
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\scheduler\multi_thread\worker.rs:447
  40: tokio::runtime::blocking::task::impl$2::poll<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0,tuple$<> >
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\blocking\task.rs:42
  41: tokio::runtime::task::core::impl$6::poll::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\core.rs:311
  42: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0> > > >::with_mut<enum2$<tokio::runtime::task::co
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\loom\std\unsafe_cell.rs:14
  43: tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task::Block
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\core.rs:300
  44: tokio::runtime::task::harness::poll_future::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\harness.rs:476
  45: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch:
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\core\src\panic\unwind_safe.rs:271
  46: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panicking.rs:500
  47: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::net::addr::impl$19::to_socket_addrs::closure_env$0>,tokio::runtime::bloc
  48: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worke
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panicking.rs:464
  49: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,toki
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panic.rs:142
  50: tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\harness.rs:464
  51: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll_inner<tokio::runtime::blocking:
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\harness.rs:198
  52: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task:
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\harness.rs:152
  53: tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\raw.rs:276
  54: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\raw.rs:200
  55: tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>::run<tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\task\mod.rs:437
  56: tokio::runtime::blocking::pool::Task::run
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\blocking\pool.rs:159
  57: tokio::runtime::blocking::pool::Inner::run
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\blocking\pool.rs:513
  58: tokio::runtime::blocking::pool::impl$6::spawn_thread::closure$0
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.29.1\src\runtime\blocking\pool.rs:471
  59: std::sys_common::backtrace::__rust_begin_short_backtrace<tokio::runtime::blocking::pool::impl$6::spawn_thread::closure_env$0,tuple$<> >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\sys_common\backtrace.rs:135
  60: std::sys_common::backtrace::__rust_begin_short_backtrace<tokio::runtime::blocking::pool::impl$6::spawn_thread::closure_env$0,tuple$<> >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\sys_common\backtrace.rs:135
  61: std::thread::impl$0::spawn_unchecked_::closure$1::closure$0<tokio::runtime::blocking::pool::impl$6::spawn_thread::closure_env$0,tuple$<> >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\thread\mod.rs:529
  62: core::panic::unwind_safe::impl$23::call_once<tuple$<>,std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tokio::runtime::blocking::pool::impl$6::spawn_thread::closure_env$0,tuple$<> > >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\core\src\panic\unwind_safe.rs:271
  63: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tokio::runtime::blocking::pool::impl$6::spawn_thread::closure_env$0,tuple$<> > >,tuple$<> >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panicking.rs:500
  64: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::net::addr::impl$19::to_socket_addrs::closure_env$0>,tokio::runtime::bloc
  65: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tokio::runtime::blocking::pool::impl$6::spawn_thread::closure_env$0,tuple$<> > > >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panicking.rs:464
  66: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\panic.rs:142
  67: std::thread::impl$0::spawn_unchecked_::closure$1<tokio::runtime::blocking::pool::impl$6::spawn_thread::closure_env$0,tuple$<> >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\std\src\thread\mod.rs:528
  68: core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<tokio::runtime::blocking::pool::impl$6::spawn_thread::closure_env$0,tuple$<> >,tuple$<> >
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398\library\core\src\ops\function.rs:250
  69: std::sys::windows::thread::impl$0::new::thread_start
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library\std\src\sys\windows\thread.rs:57
  70: BaseThreadInitThunk
  71: RtlUserThreadStart', D:\study\T-Shell-Plus\src-tauri\src\core\connect.rs:44:79
```

**Comment by Eugeny** [comment]
Enable the `openssl` crate feature if you're using RSA keys.
