### ISSUE TITLE
channel.data drops end of data

### ISSUE THREAD

**Issue by rukai** [warp-tech/russh#213]
I reproduced the problem by pulling it out of my application and into a russh example: https://github.com/rukai/russh/commit/442db2bea50a76dff545b4ebd587a13a0353cbd5

I have an implementation to write to a remote file via sending data to a remote `cat > filename`
The command completes, which I can verify by seeing that the chmod 777 has succeeded.
However on some runs the end of the file is missing.
Usually this occurs within the 50 iterations in the modified example.

From my local machine I run a command like:
`cargo run --release --example client_exec_simple -- -k ~/.ssh/id_ed25519 --username rukai pi.lan`
Which connects to my raspberry pi.
I think `--release` is important.

The application I originally encountered this on is used to setup machines in AWS.

Here is an example failed run:
```
~2/Projects/Crates/russh> cargo run --release --example client_exec_simple -- -k ~/.ssh/id_ed25519 --username rukai pi.lan
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/examples/client_exec_simple -k /home/rukai/.ssh/id_ed25519 --username rukai pi.lan`
[2023-11-09T03:52:12Z INFO  client_exec_simple] Connecting to pi.lan:22
[2023-11-09T03:52:12Z INFO  client_exec_simple] Key path: "/home/rukai/.ssh/id_ed25519"
[2023-11-09T03:52:13Z INFO  client_exec_simple] Connected
attempt #0 10485760 foo
attempt #1 10485760 foo
attempt #2 10485760 foo
attempt #3 10485760 foo
attempt #4 10485760 foo
attempt #5 10485760 foo
attempt #6 10485760 foo
attempt #7 10485760 foo
attempt #8 10485760 foo
attempt #9 10485760 foo
attempt #10 10485760 foo
attempt #11 10485760 foo
attempt #12 10485760 foo
attempt #13 10485760 foo
attempt #14 10485760 foo
attempt #15 10485760 foo
attempt #16 10485760 foo
attempt #17 10485760 foo
attempt #18 10485760 foo
attempt #19 10485760 foo
attempt #20 10485760 foo
attempt #21 10485760 foo
attempt #22 10436608 foo
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `10436608`,
 right: `10485760`', russh/examples/client_exec_simple.rs:48:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: client_exec_simple::main::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::context::runtime::enter_runtime
   7: tokio::runtime::runtime::Runtime::block_on
   8: client_exec_simple::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Eugeny** [comment]
Could you pls change the log level to LevelFilter::Debug and attach a log of it running?

**Comment by rukai** [comment]
Sure! [log.txt](https://github.com/warp-tech/russh/files/13314491/log.txt)

I wasnt sure if there were any logs that might include sensitive information so I just replaced some lines with `REDACTED` that looked like they could have keys in them

**Comment by mmirate** [comment]
I am able to reproduce this while simply sending the bytes directly to a `wc` invocation; no need to actually write anything to disk.

**I am also able to cease reproducing this by introducing a 1-second sleep between calling `channel.data` and calling `channel.eof`,** indicating that there is some kind of data race between fully writing the data through the library and writing the EOF indicator.

By adding tracing and data odometry to ChannelTx and to the two underlying Session methods (and upgrading an existing trace in the Session background task so that it would show up and the other tracing in the library would not); and adding some checking to `Encrypted::eof` which is thoroughly specific to this example usecase; I was able to produce a comparison between the final run and the final successful run.

```diff
@@ -150,6 +153,14 @@ impl Encrypted {
 
     pub fn eof(&mut self, channel: ChannelId) {
         self.byte(channel, msg::CHANNEL_EOF);
+        for (id, channel) in &self.channels {
+            for (v, ext, from) in &channel.pending_data {
+                let pending = v.len().checked_sub(*from).filter(|&x| x>0);
+                if let Some(pending) = pending {
+                    log::error!("Encrypted::eof: channel {id} still has {pending} bytes pending");
+                }
+            }
+        }
     }
 
     pub fn close(&mut self, channel: ChannelId) {
````

<details><summary>gigantic log diff, click to expand</summary><p>

```diff
--- attempt22.txt       2023-12-15 11:56:03.180056731 -0500
+++ attempt21.txt       2023-12-15 11:56:03.180056731 -0500
@@ -1,123 +1,112 @@
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 52 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 52 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 820100 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 1279356 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 2099456 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 98412 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 229628 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 328040 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 328040 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 164020 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 98412 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 82028 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 114832 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 623276 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 98412 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 98412 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 98412 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 393648 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 65608 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 65608 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 65608 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 65608 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 98412 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 393648 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 65608 bytes
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 65608 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 656080 bytes
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10027008
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10027008
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10059776
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10059776
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 459256 bytes
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10092544
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10092544
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10027008
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10059776
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10092544
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 131216 bytes
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10125312
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10125312
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 98412 bytes
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10125312
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10158080
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10158080
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10158080
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10190848
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10190848
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10027008
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10190848
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10223616
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10223616
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10059776
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10092544
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10256384
-[2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10256384
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10125312
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10158080
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10190848
 [2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10223616
+[2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10256384
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10289152
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10289152
 [2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10256384
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10321920
 [2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10289152
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10321920
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10321920
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10354688
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10321920
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10354688
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10387456
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10354688
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10387456
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10387456
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10420224
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10420224
+[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10420224
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 262432 bytes
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10452992
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10452992
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: prepping to write 32768, total bytes written will = 10485760
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 32804 bytes
 [2023-12-15T16:55:07Z INFO  russh::channels::io::tx] ChannelTx as AsyncWrite: wrote 32768, total bytes written = 10485760
 [2023-12-15T16:55:07Z INFO  client_exec_simple] about to send EOF
-[2023-12-15T16:55:07Z INFO  client_exec_simple] unhandled message Success
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 557668 bytes
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10354688
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10387456
-[2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10420224
 [2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10452992
+[2023-12-15T16:55:07Z INFO  client_exec_simple] unhandled message Success
 [2023-12-15T16:55:07Z INFO  russh::client::session] Session::data: writing 32768, total bytes written this channel = 10485760
 [2023-12-15T16:55:07Z INFO  russh::client::session] Session::eof: probably final total bytes written this channel = 10485760
-[2023-12-15T16:55:07Z ERROR russh::session] Encrypted::eof: channel 24 still has 32768 bytes pending
-[2023-12-15T16:55:07Z ERROR russh::session] Encrypted::eof: channel 24 still has 32768 bytes pending
-[2023-12-15T16:55:07Z ERROR russh::session] Encrypted::eof: channel 24 still has 32768 bytes pending
 [2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 65644 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 98412 bytes
-[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 36 bytes
 [2023-12-15T16:55:07Z INFO  client_exec_simple] got 9 bytes stdout!
+[2023-12-15T16:55:07Z INFO  russh::client] Session::run: writing to stream: 36 bytes
 [2023-12-15T16:55:07Z INFO  client_exec_simple] exited 0!
-attempt #22 10387456
+attempt #21 10485760
```

</p></details>

(I upped the buffer size to the maximum, 32768, by adding a counterpart of `channel.data` that takes an `AsyncBufRead` and runs `tokio::io::copy_buf`, and having `client_exec_simple` send it a `BufReader::with_capacity(32768, ...)`, for purposes of clarity and efficiency.)

Notice how in the failed run but not the successful run; the stream is written more than once after the EOF signal is pushed to the buffer, and when the EOF signal is pushed to the buffer, there is a channel with the same total number of bytes pending as the number of bytes that `wc` unexpectedly didn't read.
